// <auto-generated />
using System;
using FileFormatAIStudio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileFormatAIStudio.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911094500_AddModelDimensions")]
    partial class AddModelDimensions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ChatMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ChatSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedModelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.DocumentChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EmbeddingVector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("KnowledgebaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageOrSectionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_DocumentChunks_DocumentId");

                    b.HasIndex("KnowledgebaseId")
                        .HasDatabaseName("IX_DocumentChunks_KnowledgebaseId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.KnowledgebaseDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgebaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserEngineUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgebaseId")
                        .HasDatabaseName("IX_KnowledgebaseDocuments_KnowledgebaseId");

                    b.ToTable("KnowledgebaseDocuments");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.KnowledgebaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VectorDimensions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Knowledgebases");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ModelConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dimensions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmbeddingModel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ProviderConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.SessionKnowledgebaseEntity", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgebaseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "KnowledgebaseId");

                    b.HasIndex("KnowledgebaseId");

                    b.ToTable("SessionKnowledgebases");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ChatMessageEntity", b =>
                {
                    b.HasOne("FileFormatAIStudio.Data.Entities.ChatSessionEntity", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.DocumentChunkEntity", b =>
                {
                    b.HasOne("FileFormatAIStudio.Data.Entities.KnowledgebaseDocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileFormatAIStudio.Data.Entities.KnowledgebaseEntity", "Knowledgebase")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgebaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Knowledgebase");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.KnowledgebaseDocumentEntity", b =>
                {
                    b.HasOne("FileFormatAIStudio.Data.Entities.KnowledgebaseEntity", "Knowledgebase")
                        .WithMany("Documents")
                        .HasForeignKey("KnowledgebaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledgebase");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ModelConfigEntity", b =>
                {
                    b.HasOne("FileFormatAIStudio.Data.Entities.ProviderConfigEntity", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.SessionKnowledgebaseEntity", b =>
                {
                    b.HasOne("FileFormatAIStudio.Data.Entities.KnowledgebaseEntity", "Knowledgebase")
                        .WithMany("SessionKnowledgebases")
                        .HasForeignKey("KnowledgebaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileFormatAIStudio.Data.Entities.ChatSessionEntity", "Session")
                        .WithMany("SessionKnowledgebases")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledgebase");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ChatSessionEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("SessionKnowledgebases");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.KnowledgebaseDocumentEntity", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.KnowledgebaseEntity", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Documents");

                    b.Navigation("SessionKnowledgebases");
                });

            modelBuilder.Entity("FileFormatAIStudio.Data.Entities.ProviderConfigEntity", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}

